services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-5q8q.onrender.com
      - key: N8N_WEBHOOK_URL
        value: https://n8n-5q8q.onrender.com
      - key: N8N_VIEWS_URL
        value: https://n8n-5q8q.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-5q8q.onrender.com
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10
